# Generated by Django 4.1 on 2022-11-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_students_attedance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attedance',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
