# Generated by Django 4.1 on 2022-11-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_attedance_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attedance',
            name='status',
            field=models.CharField(blank=True, choices=[('absent', 'Absent'), ('present', 'Present')], max_length=8),
        ),
        migrations.AddField(
            model_name='attedance',
            name='student_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='school.students'),
            preserve_default=False,
        ),
    ]
